# Generated by Django 4.2 on 2024-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='mark',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО учащегося'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_study_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО преподавателя'),
        ),
    ]
